config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :category
	validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: true

	def day
		self.created_at.strftime("%e %b, %Y")
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
  	@entries = Entry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [ :show, :edit, :update, :destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show

  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Refeição criada com sucesso!" }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Refeição atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entrada deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
	<div class="column is-half">
		<% @entries.each do |day, entries| %>
		   <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered"> Refeições de <%= day %></h3>

		   <nav class="level is-mobile">
		   	<div class="level-item has-text-centered">
		   	  <div>
		   		<p class="heading">Calorias</p>
		   		<p class="title"><%= entries.pluck(:calories).sum %></p>
		      </div>	   		
		   	</div>
		   		<div class="level-item has-text-centered">
		   	  <div>
		   		<p class="heading">Proeteínas</p>
		   		<p class="title"><%= entries.pluck(:proteins).sum %>g</p>
		      </div>	   		
		   	</div>
		   		<div class="level-item has-text-centered">
		   	  <div>
		   		<p class="heading">Carboidratos</p>
		   		<p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
		      </div>	   		
		   	</div>
		   		<div class="level-item has-text-centered">
		   	  <div>
		   		<p class="heading">Gorduras</p>
		   		<p class="title"><%= entries.pluck(:fats).sum %>g</p>
		      </div>	   		
		   	</div>
		   </nav>

		   <% entries.each do |entry| %>
				<%= link_to entry_path(entry) do %>
				  <div class="card">
				  	<div class="card-content">
				  		<strong> <%= entry.meal_type %></strong><br/>
				  		<%= entry.calories %> calorias,
				  		<%= entry.proteins %>g proteinas,
				  		<%= entry.carbohydrates %>g carboidratos,
				  		<%= entry.fats %>g gordura
				  	</div>
				  </div>
				<% end %> 
		     <% end %>
		 <% end %>

	</div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Tipo de refeição:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Caloria:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteína:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carboidrato:</strong>
    <%= entry.carbohydrates %>
  </p>

  <p>
    <strong>Gordura:</strong>
    <%= entry.fats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p>Erro</p>
      </div class="message-body">
      <div>
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Tipo_de_refeição, class:"label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :Calorias, class:"label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :Proteínas, class:"label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :Carboidratos, class:"label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :Gorduras, class:"label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :Categoria, class:"label" %>
    <div class="select">
      <%= form.select :category_id, Category.all.collect { |u| [u.title, u.id]} %>
    </div>
  </div>

  <div>
    <br/>
    <%= form.submit class:"button is-link" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3"> Editando entrada</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= Time.now.strftime("%d-%m-%Y") %>
<% end %>

  <div class="columns mt-6 is-centered"> 
   <% @entries.each do |entry| %>
      <div class="column is-one-quarter">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title"><%= entry.meal_type %> - <%= entry.category.title if entry.category.present? %></p>
          </header>
          <div class="card-content">
            <div class="content">
              <p><span class="has-text-weight-bold"><%= entry.calories %> calorias</span></p>
              <p><span class="has-text-weight-bold"><%= entry.proteins %>
                gramas de proteínas
              </span></p>
              <p><span class="has-text-weight-bold"><%= entry.carbohydrates %>
                gramas de carboidratos
              </span></p>
              <p><span class="has-text-weight-bold"><%= entry.fats %>
                gramas de gordura
              </span></p>
              <p class="italic"> Logado <%= time_ago_in_words(entry.created_at) %> atrás</p>
            </div>
          </div>       

          <div class="card-footer">
            <%= link_to 'Exibir', entry, class:"card-footer-item" %>
            <%= link_to 'Editar', edit_entry_path(entry), class:"card-footer-item" %>
            <%= link_to 'Deletar', entry, method: :delete, data: { confirm: 'Tem certeza?'}, class:"card-footer-item" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="columns is-centered mt-6">
    <%= link_to "Todas as refeições", archives_index_path, class: "button is-link is-outlined is is-centered" %>
  </div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Nova entrada</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
	<%= @entry.meal_type %> &ndash; <%= Time.now.strftime("%d-%m-%Y") %>
<% end %>

<div class="columns mt-6 is-centered">
	<div class="column is-one-third">
		<nav class="panel is-primary">
			<p class="panel-heading">
				<%= @entry.meal_type %> :
				<%= @entry.category.title %>
			</p>

			<div class="panel-block">
				Calorias: <%= @entry.calories %>
			</div>

			<div class="panel-block">
				Proteínas: <%= @entry.proteins %>
			</div>

			<div class="panel-block">
				Carboidratos: <%= @entry.carbohydrates %>
			</div>

			<div class="panel-block">
				Gorduras: <%= @entry.fats %>
			</div>
		</nav>

		<div class="columns is-mobile">
			<div class="column">
				 <%= link_to "Editar", edit_entry_path(@entry), class: "button is-gray" %>
				 <%= link_to "Deletar", entry_path(@entry),class: "button is-gray", data: { turbo_method: :delete, turbo_confirm: "Tem certeza?"} %>
			</div>
			<div class="column">
				<!-- -->
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registro de refeições</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/header" %>

  <% if notice.present? %>
    <div class="notification is-link is-light"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
    <div class="notification is-danger is-light"><%= alert %></div>
  <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-primary is-small">
  <!-- Hero head: will stick at the top -->
  <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="container">
        <div class="navbar-brand">
          
         <%= link_to root_path, class:"navbar-item" do %>
          <svg fill="#ffffff" width="26px" height="26px" viewBox="0 0 20 20" version="1.1" xmlns="  http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
           <title>Início</title>
            <path d="M18.25,3.25 C18.6296958,3.25 18.943491,3.53215388 18.9931534,3.89822944 L19,4 L19,20 C19,20.4142136 18.6642136,20.75 18.25,20.75 C17.8703042,20.75 17.556509,20.4678461 17.5068466,20.1017706 L17.5,20 L17.5,15 L15.25,15 C14.8703042,15 14.556509,14.7178461 14.5068466,14.3517706 L14.5,14.25 L14.5,7 C14.5,4.92893219 16.1789322,3.25 18.25,3.25 Z M12.25,3.25 C12.6296958,3.25 12.943491,3.53215388 12.9931534,3.89822944 L13,4 L13,8 C13,9.95258026 11.6009489,11.5783946 9.75060185,11.9296879 L9.75,20 C9.75,20.4142136 9.41421356,20.75 9,20.75 C8.62030423,20.75 8.30650904,20.4678461 8.25684662,20.1017706 L8.25,20 L8.25039462,11.9298769 C6.46565489,11.5915104 5.10054372,10.0674505 5.00531224,8.20794855 L5,8 L5,4 C5,3.58578644 5.33578644,3.25 5.75,3.25 C6.12969577,3.25 6.44349096,3.53215388 6.49315338,3.89822944 L6.5,4 L6.5,8 C6.5,9.11956531 7.23592684,10.0672457 8.25042097,10.3856816 L8.25,4 C8.25,3.58578644 8.58578644,3.25 9,3.25 C9.37969577,3.25 9.69349096,3.53215388 9.74315338,3.89822944 L9.75,4 L9.75057321,10.3853693 C10.7082217,10.0843344 11.4174241,9.22252883 11.4932687,8.18486443 L11.5,8 L11.5,4 C11.5,3.58578644 11.8357864,3.25 12.25,3.25 Z M17.5,13.5 L17.5,4.87802928 C16.6775113,5.16873733 16.0745169,5.92410043 16.0064224,6.82871311 L16,7 L16,13.5 L17.5,13.5 L17.5,4.87802928 L17.5,13.5 Z" id="🎨-Color"></path>
          </svg>
          <span class="has-text-weight-bold is-size-4 ml-4">FoodLog</span>
          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">

              <a class="navbar-item has-text-weight-bold is-size-6 ml-4">
                <%= link_to "Cadastrar-se", new_user_registration_path, class:"navbar-item" %>
              </a>

              <a class="navbar-item has-text-weight-bold is-size-6 ml-4">
                <%= link_to "Editar usuário", edit_user_registration_path, class:"navbar-item" %>
              </a>

              <a class="navbar-item has-text-weight-bold is-size-6 ml-4">
                <%= link_to "Entrar", new_user_session_path, class:"navbar-item" %>
              </a>

              <a class="navbar-item has-text-weight-bold is-size-6 ml-4">
                <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </a>
            </div>
           </div>
         <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  
</nav>

  <!--tteste -->
  
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
          <span class="navbar-item">
            <%= link_to "Nova Refeição", new_entry_path, class:"button is-link" %>
          </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Registro de Refeições
        <% end %>
      </h1>
    </div>
  </div>
</section>